## データ読み込み

In [1]:
import json

with open("data/article_likes2.json", encoding="utf-8") as f:
    likes_data = json.load(f)

In [2]:
def summarize_likes(article_likes):
    # 取得済みのいいね情報から件数を再計算（取得漏れ確認のため）
    like_counts = [
        len(article["likes"])
        for article in article_likes.values()
    ]

    users = set()

    for article in article_likes.values():
        for like in article["likes"]:
            users.add(like["user"]["id"])

    print("記事数:", len(article_likes))
    print("最大いいね数:", max(like_counts))
    print("平均いいね数:", sum(like_counts) / len(like_counts))
    print("ユーザ数:", len(users))

summarize_likes(likes_data)

記事数: 886
最大いいね数: 577
平均いいね数: 21.959367945823928
ユーザ数: 7345

In [3]:
def filter_articles_by_likes(
    likes_data: dict,
    min_likes: int,
) -> dict:
    """いいね数が指定値以上の記事を除外する。"""

    return {
        article_id: article
        for article_id, article in likes_data.items()
        if len(article["likes"]) < min_likes
    }

# 超人気記事の影響を無くすため、いいね100以上の記事を除外する
likes_data = filter_articles_by_likes(likes_data, 100)

## ネットワーク作成

In [4]:
import networkx as nx


def create_like_network(article_likes: dict) -> nx.DiGraph:
    """
    いいね情報からユーザ→記事の有向ネットワークを作成する。

    ノード:
        記事:
            node id: article:{記事ID}
            attributes:
                type: article
                id: 記事ID
                title: 記事名

        ユーザ:
            node id: user:{ユーザID}
            attributes:
                type: user
                id: ユーザID
                name: ユーザ名
                organization: Organization名

    エッジ:
        user → article
        ユーザが記事にいいねしたことを表す
    """

    G = nx.DiGraph()

    for article_id, article in article_likes.items():

        article_node = f"article:{article_id}"

        # 記事ノード追加
        G.add_node(
            article_node,
            type="article",
            id=article_id,
            title=article["title"],
            organization=article["author_organization"]
        )

        # いいねしたユーザ
        for like in article["likes"]:
            user = like["user"]

            user_id = user["id"]
            user_node = f"user:{user_id}"

            # ユーザノード追加
            if user_node not in G:
                G.add_node(
                    user_node,
                    type="user",
                    id=user_id,
                    name=user["name"],
                    organization=user.get("organization", ""),
                )

            # ユーザ → 記事
            G.add_edge(
                user_node,
                article_node,
                type="like",
            )

    return G

In [5]:
G = create_like_network(likes_data)

print(G.nodes["article:79c4e7c3df9b6b61bbb4"])

{'type': 'article', 'id': '79c4e7c3df9b6b61bbb4', 'title': '「基本情報技術者試験をRPGで攻略する無料Webアプリを個人開発した話」', 'organization': None}

In [6]:
def get_graph_statistics(G: nx.DiGraph) -> dict:
    """グラフの基本統計量を取得する。"""

    article_nodes = [
        node for node, data in G.nodes(data=True)
        if data["type"] == "article"
    ]

    user_nodes = [
        node for node, data in G.nodes(data=True)
        if data["type"] == "user"
    ]

    return {
        # ノード
        "node_count": G.number_of_nodes(),
        "article_count": len(article_nodes),
        "user_count": len(user_nodes),

        # エッジ
        "edge_count": G.number_of_edges(),

        # 密度
        "density": nx.density(G),

        # 次数
        "average_degree": (
            sum(dict(G.degree()).values()) / G.number_of_nodes()
            if G.number_of_nodes() > 0
            else 0
        ),

        # ユーザー → 記事のエッジ
        "like_count": sum(
            1
            for _, _, data in G.edges(data=True)
            if data.get("type") == "like"
        ),
    }

stats = get_graph_statistics(G)

print(stats)

{'node_count': 5083, 'article_count': 843, 'user_count': 4240, 'edge_count': 10942, 'density': 0.0004235863338397633, 'average_degree': 4.305331497147354, 'like_count': 10942}

## 中心性を求める

In [8]:
import networkx as nx
import pandas as pd


def calculate_centralities(G: nx.DiGraph):
    """
    ネットワークの中心性を計算する。

    無向グラフにして求める。
    """

    UG = G.to_undirected()

    betweenness = nx.betweenness_centrality(UG)
    closeness = nx.closeness_centrality(UG)
    eigenvector = nx.eigenvector_centrality(
        UG,
        max_iter=1000,
        tol=1e-06,
    )

    return {
        "betweenness": betweenness,
        "closeness": closeness,
        "eigenvector": eigenvector,
    }


def create_article_df(
    G: nx.DiGraph,
    centralities: dict,
) -> pd.DataFrame:
    """
    記事ノードから記事DataFrameを作成する。

    columns:
        id
        title
        organization
        likes
        betweenness
        closeness
        eigenvector
    """

    rows = []

    for node, data in G.nodes(data=True):

        if data["type"] != "article":
            continue

        # 記事に向かうエッジ数 = いいね数
        likes = G.in_degree(node)

        rows.append(
            {
                "id": data["id"],
                "title": data["title"],
                "organization": data.get("organization", ""),
                "likes": likes,
                "betweenness": centralities["betweenness"].get(node, 0),
                "closeness": centralities["closeness"].get(node, 0),
                "eigenvector": centralities["eigenvector"].get(node, 0),
            }
        )

    return pd.DataFrame(rows)


def create_user_df(
    G: nx.DiGraph,
    centralities: dict,
    article_likes: dict,
) -> pd.DataFrame:
    """
    ユーザーノードからユーザーDataFrameを作成する。

    columns:
        id
        name
        organization
        likes
        items
        betweenness
        closeness
        eigenvector
    """

    # ユーザーごとの投稿数を取得
    # article_likes側にユーザー情報があるので、
    # user_id -> items_count の辞書を作る
    user_items_count = {}

    for article in article_likes.values():
        for like in article["likes"]:
            user = like["user"]
            user_id = user["id"]

            user_items_count[user_id] = user.get(
                "items_count",
                0,
            )

    rows = []

    for node, data in G.nodes(data=True):

        if data["type"] != "user":
            continue

        # ユーザーから記事へのエッジ数 = いいねした記事数
        likes = G.out_degree(node)

        user_id = data["id"]

        rows.append(
            {
                "id": user_id,
                "name": data["name"],
                "organization": data.get("organization", ""),
                "likes": likes,
                "items": user_items_count.get(user_id, 0),
                "betweenness": centralities["betweenness"].get(node, 0),
                "closeness": centralities["closeness"].get(node, 0),
                "eigenvector": centralities["eigenvector"].get(node, 0),
            }
        )

    return pd.DataFrame(rows)


def create_analysis_dataframes(
    article_likes: dict,
    G: nx.DiGraph,
):
    """
    Qiitaいいねネットワークから記事・ユーザーの
    DataFrameを作成する。

    Returns:
        article_df
        user_df
    """

    # 中心性をまとめて計算
    centralities = calculate_centralities(G)

    # 記事DataFrame
    article_df = create_article_df(
        G,
        centralities,
    )

    # ユーザーDataFrame
    user_df = create_user_df(
        G,
        centralities,
        article_likes,
    )

    return article_df, user_df

In [9]:
article_df, user_df = create_analysis_dataframes(
    likes_data,
    G,
)

### 中心性を分析する

### 全体

In [11]:
def get_article_rankings(
    article_df: pd.DataFrame,
    top_n: int = 5,
) -> dict[str, pd.DataFrame]:
    """記事のいいね数・各中心性ランキングを取得する。"""

    ranking_columns = [
        "likes",
        "betweenness",
        "closeness",
        "eigenvector",
    ]

    display_columns = [
        "id",
        "title",
        "organization",
        "likes",
    ]

    rankings = {}

    for column in ranking_columns:
        columns = display_columns.copy()

        if column not in columns:
            columns.append(column)

        rankings[column] = (
            article_df[columns]
            .sort_values(column, ascending=False)
            .head(top_n)
            .reset_index(drop=True)
        )

    return rankings
    
rankings = get_article_rankings(article_df, 10)

print("=== いいね数 ===")
print(rankings["likes"])

print("=== 媒介中心性 ===")
print(rankings["betweenness"])

print("=== 近接中心性 ===")
print(rankings["closeness"])

print("=== 固有ベクトル中心性 ===")
print(rankings["eigenvector"])

=== いいね数 ===
                     id                                              title  \
0  cd2c603abf8b48fc23a8                      AIが書くpandasコード、だいたい地雷が混じっている話
1  03b9b817bf2015321159                  プログラミング完全未経験から始める！競技プログラミング入門ガイド
2  c63073fef7fb87d9f472    PRを出す前にコミット履歴を整えろと先輩に叩き込まれた話 〜git rebase -i 入門〜
3  fa1f6b0db92e497796ac                      会社が変わっても消えないスキルとスタートアップという選択肢
4  01defe8188de2123b25c                        AI時代、“ITを知らない”が普通に危険になってきた話
5  996735e9b8ff4b3b1255                            要件定義とは何か？開発メンバー初心者向けガイド
6  9acccd181ca2f1a75f3c  Copilot StudioをClaude Code化したら、Copilot Studio自...
7  34010e35cd35c797d258                    【35歳未経験でも理解できた】Ruby on Rails 前編
8  6fbf02174f308e31f284  ClaudeCodeとCodexにコーディングを全て任せて商用レベルのUnityゲーム開発を...
9  f1855ff508f4268df5b5                   私の最強のMac開発環境 2026: Nixとmiseで育てる🐱

  organization  likes
0    FPT_Japan     90
1          NaN     89
2     beex-inc     88
3         prum     87
4         prum     86
5  xincere-inc     85
6          ibm     81
7         prum     78
8          NaN     73
9     nekonata     72
=== 媒介中心性 ===
                     id                                              title  \
0  cd2c603abf8b48fc23a8                      AIが書くpandasコード、だいたい地雷が混じっている話
1  1b3853a3314ab66eb2a3            TransformerのSelf AttentionのQKVを直感的に解説する
2  c63073fef7fb87d9f472    PRを出す前にコミット履歴を整えろと先輩に叩き込まれた話 〜git rebase -i 入門〜
3  026452114ad63efa9aa6                             果たしてCopilotで営業成績は上がるのか
4  6fbf02174f308e31f284  ClaudeCodeとCodexにコーディングを全て任せて商用レベルのUnityゲーム開発を...
5  9acccd181ca2f1a75f3c  Copilot StudioをClaude Code化したら、Copilot Studio自...
6  03b9b817bf2015321159                  プログラミング完全未経験から始める！競技プログラミング入門ガイド
7  f1855ff508f4268df5b5                   私の最強のMac開発環境 2026: Nixとmiseで育てる🐱
8  996735e9b8ff4b3b1255                            要件定義とは何か？開発メンバー初心者向けガイド
9  39e8e3bbc327526ac20f                          単一HTMLで作ったサイトを自己解凍形式にする試み

  organization  likes  betweenness
0    FPT_Japan     90     0.038372
1          NaN     72     0.030114
2     beex-inc     88     0.029348
3          NaN     55     0.028658
4          NaN     73     0.028395
5          ibm     81     0.028282
6          NaN     89     0.028061
7     nekonata     72     0.025855
8  xincere-inc     85     0.023608
9          NaN     52     0.023197
=== 近接中心性 ===
                     id                                             title  \
0  1b5b5016b5a74fe27fe5                   OpenAIがCodexを無料開放——これ、何が目的なんだろう
1  cd2c603abf8b48fc23a8                     AIが書くpandasコード、だいたい地雷が混じっている話
2  39e8e3bbc327526ac20f                         単一HTMLで作ったサイトを自己解凍形式にする試み
3  1b3853a3314ab66eb2a3           TransformerのSelf AttentionのQKVを直感的に解説する
4  026452114ad63efa9aa6                            果たしてCopilotで営業成績は上がるのか
5  c63073fef7fb87d9f472   PRを出す前にコミット履歴を整えろと先輩に叩き込まれた話 〜git rebase -i 入門〜
6  d7a26696d724f6e83830    社内カリキュラムが微妙だったので、「その前提知らないんだけど…」を解決する学習サイトを作った
7  a86a42a675e27853299b         Claude Code入りのDockerイメージをDevContainerで動かす
8  20bc6f13035ac3ebf468                                 Codex開発で収益化するまで#4
9  f1855ff508f4268df5b5                  私の最強のMac開発環境 2026: Nixとmiseで育てる🐱

  organization  likes  closeness
0      tomosia     48   0.292345
1    FPT_Japan     90   0.292240
2          NaN     52   0.290195
3          NaN     72   0.287230
4          NaN     55   0.284557
5     beex-inc     88   0.282813
6          NaN     33   0.281187
7          NaN     37   0.280542
8          NaN     13   0.280157
9     nekonata     72   0.280092
=== 固有ベクトル中心性 ===
                     id                                title organization  \
0  75b8ff55095604bd48b5                   PythonとJavaのコードの違い     any-plus
1  f02c34ae6dc994cd3084                   【新入社員研修】Linuxの基本操作     any-plus
2  d39b79afdbfadf5a2267                  Pythonの制御構造について【基礎】     any-plus
3  a3e11fa3d865748a5610  ビジネスマナーは“形”だけじゃない——新卒研修で学んだことと考えたこと     any-plus
4  c5d039e4efec7f0fb3f7               『入社１年目の教科書』　意識したい３つの原則     any-plus
5  46fd3c7066b0f3c1b13e                              報連相の重要性     any-plus
6  6303ef4ef36779011972        文系未経験エンジニアが研修で学んだLinuxコマンド備忘録     any-plus
7  e7939e9f2a8b3e8177f8              [初心者]Linuxと仲良くなれるコマンド3選     any-plus
8  0675640c728125a628c4               Linuxのテキストエディタ　viとnano     any-plus
9  f493dac42a3efaf4ec42             Cisco IOSモードの超ザックリとした覚え方     any-plus

   likes  eigenvector
0     56     0.148875
1     54     0.148605
2     47     0.146757
3     49     0.146540
4     46     0.146173
5     48     0.145842
6     61     0.145565
7     53     0.145354
8     45     0.144878
9     46     0.144166

### いいね

In [12]:
(article_df
.sort_values("likes", ascending=False)
.reset_index(drop=True)
).head(20)

,id,title,organization,likes,betweenness,closeness,eigenvector
0,cd2c603abf8b48fc23a8,AIが書くpandasコード、だいたい地雷が混じっている話,FPT_Japan,90,0.038372,0.292240,0.006295
1,03b9b817bf2015321159,プログラミング完全未経験から始める！競技プログラミング入門ガイド,NaN,89,0.028061,0.268560,0.005895
2,c63073fef7fb87d9f472,PRを出す前にコミット履歴を整えろと先輩に叩き込まれた話 〜git rebase -i 入門〜,beex-inc,88,0.029348,0.282813,0.007733
3,fa1f6b0db92e497796ac,会社が変わっても消えないスキルとスタートアップという選択肢,prum,87,0.018593,0.271903,0.008680
4,01defe8188de2123b25c,AI時代、“ITを知らない”が普通に危険になってきた話,prum,86,0.019713,0.270850,0.007160
5,996735e9b8ff4b3b1255,要件定義とは何か？開発メンバー初心者向けガイド,xincere-inc,85,0.023608,0.273484,0.007527
6,9acccd181ca2f1a75f3c,Copilot StudioをClaude Code化したら、Copilot Studio自...,ibm,81,0.028282,0.269983,0.003892
7,34010e35cd35c797d258,【35歳未経験でも理解できた】Ruby on Rails 前編,prum,78,0.011452,0.252507,0.005435
8,6fbf02174f308e31f284,ClaudeCodeとCodexにコーディングを全て任せて商用レベルのUnityゲーム開発を...,NaN,73,0.028395,0.271632,0.004211
9,f1855ff508f4268df5b5,私の最強のMac開発環境 2026: Nixとmiseで育てる🐱,nekonata,72,0.025855,0.280092,0.005063
10,1b3853a3314ab66eb2a3,TransformerのSelf AttentionのQKVを直感的に解説する,NaN,72,0.030114,0.287230,0.005042
11,47a13155032f716a43bd,【Claude Code / Codex × GAS】コピペ脱出！Google Worksp...,jqiit-co,70,0.014473,0.234541,0.000887
12,6303ef4ef36779011972,文系未経験エンジニアが研修で学んだLinuxコマンド備忘録,any-plus,61,0.007836,0.261692,0.145565
13,f6edd279d32102e6f5a8,ChatGPT Pro は高いので Codex + GitHub Copilot でお小遣い...,NaN,60,0.015609,0.230713,0.000338
14,ac378f83a4e7911392d4,クオンツトレード入門者のための確率過程――価格予測ではなく、分布・リスク・エッジを見るために,NaN,60,0.022577,0.268324,0.003817
15,75b8ff55095604bd48b5,PythonとJavaのコードの違い,any-plus,56,0.005985,0.261245,0.148875
16,323bc76cf2d31d9f4d42,育休中エンジニアがClaude Coworkで「あかちゃんカレンダー🍼」を作った話,works-hi,56,0.014619,0.268353,0.005247
17,ccbdbe70817ece37cfdb,2025 Japan AWS Jr. Champions としての活動が終了しました,aws-jr-champions,56,0.016278,0.267210,0.004193
18,026452114ad63efa9aa6,果たしてCopilotで営業成績は上がるのか,NaN,55,0.028658,0.284557,0.004818
19,f02c34ae6dc994cd3084,【新入社員研修】Linuxの基本操作,any-plus,54,0.005956,0.263468,0.148605

### 媒介

In [13]:
(article_df
.sort_values("betweenness", ascending=False)
.reset_index(drop=True)
).head(20)

,id,title,organization,likes,betweenness,closeness,eigenvector
0,cd2c603abf8b48fc23a8,AIが書くpandasコード、だいたい地雷が混じっている話,FPT_Japan,90,0.038372,0.292240,0.006295
1,1b3853a3314ab66eb2a3,TransformerのSelf AttentionのQKVを直感的に解説する,NaN,72,0.030114,0.287230,0.005042
2,c63073fef7fb87d9f472,PRを出す前にコミット履歴を整えろと先輩に叩き込まれた話 〜git rebase -i 入門〜,beex-inc,88,0.029348,0.282813,0.007733
3,026452114ad63efa9aa6,果たしてCopilotで営業成績は上がるのか,NaN,55,0.028658,0.284557,0.004818
4,6fbf02174f308e31f284,ClaudeCodeとCodexにコーディングを全て任せて商用レベルのUnityゲーム開発を...,NaN,73,0.028395,0.271632,0.004211
5,9acccd181ca2f1a75f3c,Copilot StudioをClaude Code化したら、Copilot Studio自...,ibm,81,0.028282,0.269983,0.003892
6,03b9b817bf2015321159,プログラミング完全未経験から始める！競技プログラミング入門ガイド,NaN,89,0.028061,0.268560,0.005895
7,f1855ff508f4268df5b5,私の最強のMac開発環境 2026: Nixとmiseで育てる🐱,nekonata,72,0.025855,0.280092,0.005063
8,996735e9b8ff4b3b1255,要件定義とは何か？開発メンバー初心者向けガイド,xincere-inc,85,0.023608,0.273484,0.007527
9,39e8e3bbc327526ac20f,単一HTMLで作ったサイトを自己解凍形式にする試み,NaN,52,0.023197,0.290195,0.005275
10,ac378f83a4e7911392d4,クオンツトレード入門者のための確率過程――価格予測ではなく、分布・リスク・エッジを見るために,NaN,60,0.022577,0.268324,0.003817
11,1b5b5016b5a74fe27fe5,OpenAIがCodexを無料開放——これ、何が目的なんだろう,tomosia,48,0.020836,0.292345,0.006950
12,2dc91c5217ae52ef16c1,カフェで見る「Wi-Fi接続QRコード」の仕組みを調べてみた,palettelink_skillshare,50,0.020260,0.270910,0.004452
13,01defe8188de2123b25c,AI時代、“ITを知らない”が普通に危険になってきた話,prum,86,0.019713,0.270850,0.007160
14,fa1f6b0db92e497796ac,会社が変わっても消えないスキルとスタートアップという選択肢,prum,87,0.018593,0.271903,0.008680
15,d0ad5d691790ff0eca71,Claude Platform on AWSをエンタープライズ企業で利用する上での考慮点と、...,tisi-inc,49,0.017364,0.276015,0.004425
16,ccbdbe70817ece37cfdb,2025 Japan AWS Jr. Champions としての活動が終了しました,aws-jr-champions,56,0.016278,0.267210,0.004193
17,f6edd279d32102e6f5a8,ChatGPT Pro は高いので Codex + GitHub Copilot でお小遣い...,NaN,60,0.015609,0.230713,0.000338
18,a86a42a675e27853299b,Claude Code入りのDockerイメージをDevContainerで動かす,NaN,37,0.015537,0.280542,0.004398
19,a5234436a61194e24df7,出たてほやほやのClaude Opus 4.8を整理してみた,kddiagile,48,0.015394,0.274929,0.004383

### 近接

In [14]:
(article_df
.sort_values("closeness", ascending=False)
.reset_index(drop=True)
).head(40)

,id,title,organization,likes,betweenness,closeness,eigenvector
0,1b5b5016b5a74fe27fe5,OpenAIがCodexを無料開放——これ、何が目的なんだろう,tomosia,48,0.020836,0.292345,0.006950
1,cd2c603abf8b48fc23a8,AIが書くpandasコード、だいたい地雷が混じっている話,FPT_Japan,90,0.038372,0.292240,0.006295
2,39e8e3bbc327526ac20f,単一HTMLで作ったサイトを自己解凍形式にする試み,NaN,52,0.023197,0.290195,0.005275
3,1b3853a3314ab66eb2a3,TransformerのSelf AttentionのQKVを直感的に解説する,NaN,72,0.030114,0.287230,0.005042
4,026452114ad63efa9aa6,果たしてCopilotで営業成績は上がるのか,NaN,55,0.028658,0.284557,0.004818
5,c63073fef7fb87d9f472,PRを出す前にコミット履歴を整えろと先輩に叩き込まれた話 〜git rebase -i 入門〜,beex-inc,88,0.029348,0.282813,0.007733
6,d7a26696d724f6e83830,社内カリキュラムが微妙だったので、「その前提知らないんだけど…」を解決する学習サイトを作った,NaN,33,0.014010,0.281187,0.005887
7,a86a42a675e27853299b,Claude Code入りのDockerイメージをDevContainerで動かす,NaN,37,0.015537,0.280542,0.004398
8,20bc6f13035ac3ebf468,Codex開発で収益化するまで#4,NaN,13,0.005162,0.280157,0.004187
9,f1855ff508f4268df5b5,私の最強のMac開発環境 2026: Nixとmiseで育てる🐱,nekonata,72,0.025855,0.280092,0.005063
10,d77557170777d79e1fc9,fix というコミットメッセージを書くなと先輩に叩き込まれた話 〜未来の自分を助けるコミット...,beex-inc,50,0.014955,0.278720,0.007694
11,ec04f8d5c110a9927498,CORSを一緒に理解しよう（Cross-Origin Resource Sharing）,tomosia,40,0.013110,0.277707,0.006065
12,193360dcb3e18c8c96ac,「あなたの絵には価値がある」を形にした。お絵描きSNS『画HACK』を開発しました,NaN,26,0.011585,0.277392,0.006189
13,38757bc86c30f0326519,【TypeScript】条件分岐のベストプラクティス ── ネスト・switch・フラグ引数...,xincere-inc,39,0.009287,0.276358,0.006877
14,d0ad5d691790ff0eca71,Claude Platform on AWSをエンタープライズ企業で利用する上での考慮点と、...,tisi-inc,49,0.017364,0.276015,0.004425
15,c7f5838aef1afea9f631,React開発者注意：TanStack Router攻撃事件まとめ,tomosia,29,0.006626,0.275393,0.005318
16,a5234436a61194e24df7,出たてほやほやのClaude Opus 4.8を整理してみた,kddiagile,48,0.015394,0.274929,0.004383
17,02973ecea78afb27e641,Markdownの太字は、なぜ日本語の鉤括弧で壊れるのか,adixi,33,0.013817,0.274898,0.003973
18,1d402ce59b8d9153288e,番外編：開発技術のパラダイムシフト⑤,onewedge,11,0.003124,0.273974,0.004582
19,996735e9b8ff4b3b1255,要件定義とは何か？開発メンバー初心者向けガイド,xincere-inc,85,0.023608,0.273484,0.007527
20,fd1be5f3be4170a11a44,Agent Toolkit for AWSが持つ50種類のSkillsをStrands Ag...,tisi-inc,25,0.006187,0.273423,0.003561
21,00abdf19123dcd33333b,AWS・Azure・GCPのネットワーク設計思想をIPレベルから比較する ~各サービスの比較...,NaN,22,0.007963,0.271934,0.004668
22,fa1f6b0db92e497796ac,会社が変わっても消えないスキルとスタートアップという選択肢,prum,87,0.018593,0.271903,0.008680
23,8607bf9f2683fb8442de,Claude Code はセッションをまたぐと記憶がリセットされる — 5分で永続記憶を仕込む方法,jqiit-co,45,0.011843,0.271692,0.004369
24,eee9eb3840d3f740f325,AWS上にセキュアかつ安価かつ使い捨て可能なリモート開発環境を構築した話 ― SSM × S...,NaN,20,0.005989,0.271632,0.003332
25,6fbf02174f308e31f284,ClaudeCodeとCodexにコーディングを全て任せて商用レベルのUnityゲーム開発を...,NaN,73,0.028395,0.271632,0.004211
26,f4531c7266702b1419f8,【図解】IT初心者でもわかる！クリーンアーキテクチャの基本,cleaveware,38,0.011159,0.271511,0.005767
27,42b52dfff934785c5f31,Node.jsでDateに代わる日時処理として実装された「Temporal」を触ってみた,NaN,14,0.003957,0.271360,0.005368
28,2dc91c5217ae52ef16c1,カフェで見る「Wi-Fi接続QRコード」の仕組みを調べてみた,palettelink_skillshare,50,0.020260,0.270910,0.004452
29,4e7c37c338fb41a275cb,離島に移住してニートしながら個人開発した話,NaN,35,0.011449,0.270880,0.003955
30,01defe8188de2123b25c,AI時代、“ITを知らない”が普通に危険になってきた話,prum,86,0.019713,0.270850,0.007160
31,a8230f78084612e4e9e1,就活中のジュニアエンジニアが面接で痛感した「力不足」の話,dotlog-dev,32,0.011713,0.270610,0.005855
32,bdbd01449cf019365dca,Generative UIでSuspenseを使う,NaN,17,0.005838,0.270400,0.003923
33,f6e22db9ecb9550e37f6,現場1、2年目に伝えたい、Viコマンドが自分のエンジニア人生を変えた話,jqiit-co,46,0.011151,0.270251,0.005148
34,d3283a82c1f9ed9d3cc0,Excelの実体って結局何なのか？が気になった話,NaN,42,0.013340,0.270251,0.007075
35,9acccd181ca2f1a75f3c,Copilot StudioをClaude Code化したら、Copilot Studio自...,ibm,81,0.028282,0.269983,0.003892
36,b46711e39fb8ab50a708,【2026年最新】Copilot Studio ライセンス完全ガイド ─ 大企業が「損しない...,NaN,24,0.007926,0.269715,0.002956
37,fa88ac0b9b7eb7fd7b7e,[Frontend Performance - Part 17] 最適化の前に計測せよ：Ch...,tomosia,17,0.002962,0.269388,0.004329
38,313779e2d3feadfefa7e,Pythonの標準出力をもっと美しく。`Rich` で作るモダンなCLIツール入門,NaN,42,0.013583,0.268884,0.003467
39,746fc38b5675869b96a0,AI Ready なデータ基盤とは何か,microsoft,40,0.014798,0.268766,0.003452

### 固有ベクトル

In [15]:
(article_df
.sort_values("eigenvector", ascending=False)
.reset_index(drop=True)
).head(40)

,id,title,organization,likes,betweenness,closeness,eigenvector
0,75b8ff55095604bd48b5,PythonとJavaのコードの違い,any-plus,56,5.984536e-03,0.261245,0.148875
1,f02c34ae6dc994cd3084,【新入社員研修】Linuxの基本操作,any-plus,54,5.955867e-03,0.263468,0.148605
2,d39b79afdbfadf5a2267,Pythonの制御構造について【基礎】,any-plus,47,2.061160e-03,0.254160,0.146757
3,a3e11fa3d865748a5610,ビジネスマナーは“形”だけじゃない——新卒研修で学んだことと考えたこと,any-plus,49,2.984651e-03,0.255380,0.146540
4,c5d039e4efec7f0fb3f7,『入社１年目の教科書』 意識したい３つの原則,any-plus,46,2.443174e-03,0.256748,0.146173
5,46fd3c7066b0f3c1b13e,報連相の重要性,any-plus,48,3.068058e-03,0.258594,0.145842
6,6303ef4ef36779011972,文系未経験エンジニアが研修で学んだLinuxコマンド備忘録,any-plus,61,7.836424e-03,0.261692,0.145565
7,e7939e9f2a8b3e8177f8,[初心者]Linuxと仲良くなれるコマンド3選,any-plus,53,4.095105e-03,0.253422,0.145354
8,0675640c728125a628c4,Linuxのテキストエディタ viとnano,any-plus,45,1.398766e-03,0.247775,0.144878
9,f493dac42a3efaf4ec42,Cisco IOSモードの超ザックリとした覚え方,any-plus,46,4.703957e-04,0.194544,0.144166
10,80347bcd89a8a51c0298,データベース新卒研修まとめ,any-plus,44,1.769261e-03,0.254081,0.143926
11,174792be640713601f26,相対パスを使ってcd ..\..\〇〇と書けることを知らなかったのでメモ,any-plus,43,1.251059e-03,0.250567,0.142746
12,227c9bd2cf58d99a6033,Linuxと仲良くなりたい,any-plus,48,1.339208e-03,0.221600,0.142620
13,d942ba887cf78ae0c937,コミュニケーションは大事,any-plus,45,2.403986e-03,0.250233,0.141239
14,29d3b6b82a8bb1f14ca8,Pythonのリストって？,any-plus,42,1.222031e-03,0.247424,0.140857
15,9f171530581bc74723fd,初心者のためのLinux,any-plus,40,7.813028e-04,0.210899,0.131565
16,d283e5b20132a1be5af4,ToDoリストアプリの仕組み,any-plus,38,1.598329e-03,0.223544,0.130585
17,ae67cc9245f70fa1c283,報連相で注意を受けないために,any-plus,38,4.235292e-04,0.183896,0.129235
18,e562360142b8bdca5ceb,初級！！！IPv4アドレスについて！,any-plus,40,2.759974e-04,0.202501,0.128594
19,d39e3ec9d767ee100fe8,コミュニケーションの基本,any-plus,36,6.370160e-06,0.184604,0.128463
20,4286321d819e52c8a49a,新卒DB研修 ーSQLとは何かー,any-plus,37,9.743956e-04,0.213775,0.126192
21,715768e52d170333fb54,仕事の要！報連相！,any-plus,35,4.720785e-04,0.213738,0.122475
22,bd99ea8a936dae91601c,【超初心者】３つのルーターで冗長化してみよう【ネットワーク】,any-plus,36,1.442154e-04,0.197929,0.122280
23,21d9d10aa736d827071a,新卒が研修で習った「IPアドレス」と「サブネットマスク」について説明する,any-plus,36,1.754665e-04,0.185121,0.122159
24,8b0f6acef757a29654ac,Pythonのまとめ,any-plus,34,2.344356e-04,0.213719,0.119849
25,a45310401a411d5f7d26,Pythonで電卓を作ったよ,any-plus,35,1.430209e-04,0.192675,0.117878
26,dcd213465085b795f1a0,ネットワーク～管理系の設定を入れてみよう～,any-plus,30,4.435785e-04,0.185037,0.093135
27,e9dc4032ec618bb14538,Ubuntu 26.04 LTSでもNvidia等のドライバをGUIから管理したい(←今は無...,any-plus,6,1.083267e-07,0.182483,0.021710
28,fa1f6b0db92e497796ac,会社が変わっても消えないスキルとスタートアップという選択肢,prum,87,1.859324e-02,0.271903,0.008680
29,c63073fef7fb87d9f472,PRを出す前にコミット履歴を整えろと先輩に叩き込まれた話 〜git rebase -i 入門〜,beex-inc,88,2.934826e-02,0.282813,0.007733
30,d77557170777d79e1fc9,fix というコミットメッセージを書くなと先輩に叩き込まれた話 〜未来の自分を助けるコミット...,beex-inc,50,1.495512e-02,0.278720,0.007694
31,996735e9b8ff4b3b1255,要件定義とは何か？開発メンバー初心者向けガイド,xincere-inc,85,2.360772e-02,0.273484,0.007527
32,01defe8188de2123b25c,AI時代、“ITを知らない”が普通に危険になってきた話,prum,86,1.971325e-02,0.270850,0.007160
33,d3283a82c1f9ed9d3cc0,Excelの実体って結局何なのか？が気になった話,NaN,42,1.333970e-02,0.270251,0.007075
34,1b5b5016b5a74fe27fe5,OpenAIがCodexを無料開放——これ、何が目的なんだろう,tomosia,48,2.083574e-02,0.292345,0.006950
35,38757bc86c30f0326519,【TypeScript】条件分岐のベストプラクティス ── ネスト・switch・フラグ引数...,xincere-inc,39,9.286579e-03,0.276358,0.006877
36,bac7a492b1b7d5ffe510,Qiita記事の毎月投稿を三年間継続できたので振り返ります！,NaN,34,1.033289e-02,0.264465,0.006472
37,cd2c603abf8b48fc23a8,AIが書くpandasコード、だいたい地雷が混じっている話,FPT_Japan,90,3.837166e-02,0.292240,0.006295
38,193360dcb3e18c8c96ac,「あなたの絵には価値がある」を形にした。お絵描きSNS『画HACK』を開発しました,NaN,26,1.158505e-02,0.277392,0.006189
39,ec04f8d5c110a9927498,CORSを一緒に理解しよう（Cross-Origin Resource Sharing）,tomosia,40,1.311005e-02,0.277707,0.006065